### ISSUE TITLE
Create a function to receive stripe hook and

### ISSUE THREAD

**Issue by gimyboya** [an-nadaaa/nda-front#38]
When a successful stripe payment happens. We update the raised amount accordingly to reflect the donation on the website.

**Comment by an-nadaa** [comment]
@smsalmanshahAN I Have done this and tested it on development. we need to test it in prod and for such we need:
- At least one cause created for production and published
- Perform a donation and see if it is reflected on the cause page/card

**Comment by gimyboya** [comment]
@an-nadaa @smsalmanshah to your attention please

**Comment by smsalmanshahAN** [comment]
I have selected Hospital campaign but on stripe checkout it is linking with Ramadan project.

![image](https://user-images.githubusercontent.com/101787508/161360050-8a465509-d39d-4d70-8e1e-fb3da146e8fb.png)
